
upstream api_gateway {
    server api-gateway:8000;
}

upstream auth_service {
    server auth-service:8001;
}

server {
    listen 80;
    server_name localhost;

    client_max_body_size 20M;

    location / {
        proxy_pass http://api_gateway;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    location /nginx-health {
        access_log off;
        return 200 "ok\n";
        add_header Content-Type text/plain;
    }
}

