services:

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"   
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

    networks:
      - app-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:24
    container_name: clickhouse
    restart: unless-stopped
    volumes:
        - clickhouse_data:/var/lib/clickhouse
    ports:
        - "8123:8123"
    networks:
        - app-network
    healthcheck:
        test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
        interval: 10s
        timeout: 5s
        retries: 5

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network


  auth-service:
    build: ../services/auth-service
    ports:
      - "8001:8000"
    container_name: auth-service
    restart: unless-stopped
    env_file: ../services/auth-service/.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  api-gateway:
     build: ../services/api-gateway
     container_name: api-gateway
     restart: unless-stopped
     env_file: ../services/api-gateway/.env
     depends_on:
       redis:
         condition: service_healthy
     networks:
       - app-network

  # integration-service:
  #   build: ../services/integration-service
  #   container_name: integration-service
  #   restart: unless-stopped
  #   env_file: ../services/integration-service/.env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # sync-worker:
  #   build: ../services/sync-worker
  #   container_name: sync-worker
  #   restart: unless-stopped
  #   env_file: ../services/sync-worker/.env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # normalization-service:
  #   build: ../services/normalization-service
  #   container_name: normalization-service
  #   restart: unless-stopped
  #   env_file: ../services/normalization-service/.env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     clickhouse:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # analytics-service:
  #   build: ../services/analytics-service
  #   container_name: analytics-service
  #   restart: unless-stopped
  #   env_file: ../services/analytics-service/.env
  #   depends_on:
  #     clickhouse:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # manual-input-service:
  #   build: ../services/manual-input-service
  #   container_name: manual-input-service
  #   restart: unless-stopped
  #   env_file: ../services/manual-input-service/.env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # reporting-service:
  #   build: ../services/reporting-service
  #   container_name: reporting-service
  #   restart: unless-stopped
  #   env_file: ../services/reporting-service/.env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # notification-service:
  #   build: ../services/notification-service
  #   container_name: notification-service
  #   restart: unless-stopped
  #   env_file: ../services/notification-service/.env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - app-network

  # scheduler-service:
  #   build: ../services/scheduler-service
  #   container_name: scheduler-service
  #   restart: unless-stopped
  #   env_file: ../services/scheduler-service/.env
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #     rabbitmq:
  #       condition: service_healthy
  #   networks:
  #     - app-network

networks:       
  app-network:
    driver: bridge

volumes:           # ← вот сюда, в самый конец, без отступа
  redis_data:
  postgres_data:
  clickhouse_data:
  rabbitmq_data: